
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://htgvzpqgysbjvgnqlwle.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh0Z3Z6cHFneXNianZnbnFsd2xlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc5NDgyOTAsImV4cCI6MjA2MzUyNDI5MH0.F3MQVkuuW7pNUVxal-U2xOODKMbL4wywm4uabzDMnMk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
